# Setup
title: "[quantify.humanity]"
#~ tagline: ...to fix it. # Thoughts on the human condition.
description: "Make each day count. Save the world. "
url: https://blog.quanthum.com
paginate: 1
baseurl: ""
permalink: /:title
host: 0.0.0.0 # https://stackoverflow.com/questions/16608466/connect-to-a-locally-built-jekyll-server-using-mobile-devices-in-the-lan

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Laurent Yim
  url: https://twitter.com/quant_hum
  email: blog@quanthum.com

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/poole/poole
